# Bun test configuration

[test]
# Run tests in watch mode by default during development
# watch = true

# Test coverage settings
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { line = 80 }

# Test timeout
timeout = 5000

# Test file patterns
include = ["**/*.test.ts", "**/*.spec.ts"]
exclude = ["node_modules/**", ".next/**", "dist/**"]

# Environment for tests
env = { "NODE_ENV" = "test" }

# Preload files
preload = ["./tests/setup.ts"]